version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=chimovies
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql